version: '3'  
services:
  app:
    build: .
    container_name: carset-task-manager
    environment:
      - MONGO_URI=mongodb://mongo:27017/carsetdb
      - JWT_SECRET=supersecretkey123
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: carset-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret123
      - MONGO_DB:carset-task
    ports:
      -"27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
